name: Build Android applications

on: workflow_call

jobs:
  init:
    name: Initialize Android application builds
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-apps.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Find all Android applications
        id: find-apps
        run: |
          find android -mindepth 1 -maxdepth 1 -name '*.sh' \
            | sed 's|^android/||' \
            | sed 's|\.sh$||' \
            | jq -R \
            | jq -cs '{ "application": . }' \
            > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build:
    name: Build all applications
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu

      - name: Run the build script
        run: |
          cd android
          bash "${{ matrix.application }}.sh"

      - name: Upload application as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.application }}
          path: android/${{ matrix.application }}.apk

  register:
    name: Register all applications
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: android-*

      - name: Install latest version of fdroidserver
        run: |
          sudo pip install git+https://gitlab.com/fdroid/fdroidserver.git
          fdroid --version

      - name: Copy all applications into repository directory
        run: |
          mkdir ./android
          cp ./artifacts/*/*.apk ./android

      - name: Upload the resulting repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: android
