name: Deploy to Netlify

on: workflow_call

jobs:
  main:
    name: Depoly to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Write repository public key
        run: |
          echo "${{ secrets.RANGHO_REPOSITORY_SIGNING_PGP_PUBLIC }}" > public.asc

      - name: Download Arch Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: arch
          path: arch

      - name: Download Void Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: void
          path: void

      - name: Upload all build artifacts to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: .
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.RANGHO_REPOSITORY_NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.RANGHO_REPOSITORY_NETLIFY_ID }}
        
